os:
    - linux
language: node_js
node_js:
    - "12.16.1"
jdk:
    - oraclejdk8
cache:
    yarn: true
    directories:
        - node_modules
        - $HOME/.m2
env:
    matrix:
        - JHIPSTER_VERSION=6.0.0
        - JHIPSTER_VERSION=latest
    global:
        - JHIPSTER_TRAVIS=$TRAVIS_BUILD_DIR/travis
before_install:
    - yarn global add yo
install:
    - yarn install
    - yarn test
    - yarn link
before_script:
    - rm -r test
script:
    - jdk_switcher use oraclejdk8
    - $JHIPSTER_TRAVIS/run-test-case.sh
notifications:
    email: false
